exclude: ['config.yml', '.gitignore', 'Gemfile', 'Gemfile.lock']

pygments: true
lsi: true
future: false
markdown: maruku
permalink: pretty
permalink: /blog/:categories/:year/:month/:day/:title.html

paginate: 10
